# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1
      with:
        go-version-file: 'go.mod'
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        check-latest: false # optional
        # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
        architecture: x64 # optional

    - name: Install dependencies
      run: |
        go get .

    - name: Build
      run: go build -v ./...
